### ISSUE TITLE
Add the projects data for the pod !

### ISSUE THREAD

**Issue by siddhi-244** [MLH-Fellowship/prep-portfolio-22.OCT.PREP.1#26]
The projects data in this portfolio is not what our pod is working on , so I want to change that and add the projects on which we are currently working.

**Comment by siddhi-244** [comment]
@akshitadixit I did discus this with my teammate . As this is a small issue, I would like to work on it alone !

**Comment by akshitadixit** [comment]
Make sure you keep a tab on #6 as well

**Comment by siddhi-244** [comment]
> Make sure you keep a tab on #6 as well

Sure !
