### ISSUE TITLE
Add provision for Project Setup with Docker 

### ISSUE THREAD

**Issue by Neelaksh-Singh** [MLH-Fellowship/prep-portfolio-22.OCT.PREP.1#32]
## Issue Description
Seeing some of the folks initially struggle with setup environment, I started to look into a containerized approach of doing the setup rather than the bare-metal way. 
Also some of the developers prefer to test the project before jumping into it. Therefore to get a feel of it, they would go for a quick and easy setup of the development environment, without the hassle of installing all the libraries and dependencies on their local system.

## How does it solve the above problem?
This shrinks the installation process to just 2 steps. A developer can focus on development aspect of project and not worry about redundancy issues, dependencies issues and all that headache. Since it would automatically mount the repo on top of the container, developer could simply start developing on the cloned repo itself, save it and refresh the browser for updated changes. All the compilation, rendering, etc would be handled by the container.

**Comment by akshitadixit** [comment]
Very well thought of!

**Comment by akshitadixit** [comment]
Additionally, after @niyoj adds the 'loading screen' thing, during the loading animation we could add a small statement "this project is dockerized" to direct attention towards it.

**Comment by Neelaksh-Singh** [comment]
Sounds cool
