### ISSUE TITLE
Merge podmates photos with their description tiles

### ISSUE THREAD

**Issue by akshitadixit** [MLH-Fellowship/prep-portfolio-22.OCT.PREP.1#46]
Currently the podmates tiles and their photos are separate. We could create cards, scrollable horizontally with their photos and all their links. LMK if this needs more description.

**Comment by siddhi-244** [comment]
![Screenshot (371)](https://user-images.githubusercontent.com/69195262/194708735-ffdc96d1-6143-4f55-b3ef-515b6055738e.png)
this works @akshitadixit ?

**Comment by siddhi-244** [comment]
if this works ! Assign me this one !

**Comment by akshitadixit** [comment]
Yes, but then make sure the photos aren't there in the header anymore!

**Comment by siddhi-244** [comment]
> Yes, but then make sure the photos aren't there in the header anymore!

Cool ! I will look into it !
